.TH ttv 1 "(c) 2001 Gerd Knorr"
.SH NOM
ttv - affiche la TV/vidéo sur une console
.SH SYNOPSIS
.B ttv  [ options ] [ nom de l'émetteur ]
.SH DESCRIPTION
.B ttv
affiche la TV/vidéo sur une console, les images sont rendues
en utilisant aalib.
.SH OPTIONS
.TP
.B -h
affiche un texte d'aide.
.TP
.B -f
utilisant la fonction de conversion rapide d'aalib.
.TP
.B -c périphérique
périphérique video4linux (par défaut /dev/video0).
.P
Il y a aussi plein d'options pour aalib, lisez la documentation
d'aalib pour plus de détails là-dessus. Le texte d'aide inclut une
liste.
.SH VOIR AUSSI
xawtv(1), fbtv(1)
.SH AUTEUR
Gerd Knorr <kraxel@bytesex.org>
.SH TRADUCTEUR
José Jorge <jjorge at free.fr>
.SH COPYRIGHT
Copyright (C) 2000 Gerd Knorr <kraxel@bytesex.org>
.P
Ce programme est un logiciel libre\ ; vous pouvez le redistribuer et/ou
le modifier sous les termes de la licence GNU GPL telle que publiée
par la Free Software Foundation\ ; soit la version 2, soit (à votre convenance)
toute version ultérieure.
.P
Ce programme est distribué dans l'espoir qu'il soit utile, mais
SANS AUCUNE GARANTIE; même sans la garantie implicite de UTILISABILITÉ
ou d'ADAPTATION À UN USAGE PRÉCIS. Lisez la licence GNU GPL pour plus
de détails.
.P
Vous devriez avoir reçu une copie de la licence GNU GPL avec ce programme\ ;
si ce n'est pas le cas, écrivez à Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.



